package:
   name: intake-streamz
   version: {{ GIT_DESCRIBE_TAG }}

source:
   path: ..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python

requirements:
  build:
    - python
    - jinja2
    - streamz
  run:
    - intake>=0.5
    - python
    - streamz>=0.5.1

test:
  source_files:
    - tests
  requires:
    - pytest
    - pytest-cov
    - coverage
  commands:
    - py.test --verbose --cov=intake_streamz tests

about:
  home: https://github.com/intake/intake-streamz
  license: BSD
  license_file: LICENSE
  summary: |
    streamz
