name: CI

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  test:
    name: ${{ matrix.CONDA_ENV }}-pytest
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        CONDA_ENV: [py37, py38, py39]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: false
          activate-environment: test_env
          environment-file: ci/environment-${{ matrix.CONDA_ENV }}.yml

      - name: Development Install
        shell: bash -l {0}
        run: |
          python -m pip install --no-deps -e .
          conda list

      - name: Run Tests
        shell: bash -l {0}
        run: |
          pytest --verbose
